#!/bin/zsh

assert() {
       if [[ "$2" != "$3" ]]; then
       	   echo "Failure: $1\n\tExpected: $3\n\tReceived: $2"
	   ERR=1
       fi
}

function teardown() {
    cd "$DIR"
    rm -f a b
}

CORPUS=$(realpath corpus)
FS=$'\034'
DIR=$(mktemp -d)
trap "rm -rf $DIR" EXIT
cd "$DIR"

AHEAD="${FS}a\n"
BHEAD="${FS}b\n"

assert 'charset' "$($CORPUS charset <(echo "aba\nab$FS"))" "$(echo "\n 2\n^\\\\ 1\na 3\nb 2")"

echo 'aaa' > a
echo 'bbb' > b
assert 'merge' "$($CORPUS merge a b)" "$(echo "${AHEAD}aaa\n${BHEAD}bbb")"
teardown

assert 'mwe' "$($CORPUS mwe "a b" "d / e" < <(echo "${FS}a b\na b a  b c d / e"))" "$(echo "${FS}a b\na_b a_b c d_/_e")"

echo "${FS}a\naaa\n${FS}b\nbbb" | $CORPUS split
[[ -f a ]]
assert 'split a' $? 0
[[ -f b ]]
assert 'split b' $? 0
assert 'split a contents' "$(cat a)" 'aaa'
assert 'split b contents' "$(cat b)" 'bbb'
teardown

[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"


