#!/bin/zsh

assert() {
       if [[ "$2" != "$3" ]]; then
       	   echo "Failure: $1\n\tExpected: $3\n\tReceived: $2"
	   ERR=1
       fi
}

function teardown() {
    cd "$DIR"
    rm -f a b
}

CORPUS=$(realpath corpus)
FS=$'\034'
DIR=$(mktemp -d)
trap "rm -rf $DIR" EXIT
cd "$DIR"

AHEAD="${FS}a\n"
BHEAD="${FS}b\n"

#charset
assert 'charset' "$($CORPUS charset <(echo "aba\nab$FS"))" "$(echo "$'\\\\\\\010' 2\n$'\\\\\\\028' 1\na 3\nb 2")"

#kwik
assert kwic "$($CORPUS kwic -w 2 b <(echo "a a a b c c c"))" 'a a b c c'
#assert 'kwic multiline' "$($CORPUS kwic -w 1 b <(echo "a b\nc x b z"))" 'x b z'
assert 'kwic tokens no lines' "$($CORPUS kwic -w 1 b <(echo 'a b c d e b g'))" "$(echo 'a b c\ne b g')"

#mangle2
assert 'mangle single unigram' "$(echo 'a' | $CORPUS mangle a)" "$(echo 'a0')"
assert 'mangle unigram ignores others' "$(echo 'a\nb\nc' | $CORPUS mangle b)" "$(echo 'a\nb0\nc')"
assert 'mangle unigram multiple' "$(echo 'a\nb\nc\nb\nd' | $CORPUS mangle b)" "$(echo 'a\nb0\nc\nb1\nd')"
assert 'mangle single bigram' "$(echo 'a\nb' | $CORPUS mangle a b)" "$(echo 'a0\nb1')"
assert 'mangle other words left alone' "$(echo 'a\nb\nc\nd' | $CORPUS mangle b c)" "$(echo 'a\nb0\nc1\nd')"
assert 'mangle larger window' "$(echo 'a\nb\nc\nd' | $CORPUS mangle a d 3)" "$(echo 'a0\nb\nc\nd1')"

#merge
echo 'aaa' > a
echo 'bbb' > b
assert 'merge' "$($CORPUS merge a b)" "$(echo "${AHEAD}aaa\n${BHEAD}bbb")"
teardown

#mwe
assert 'mwe' "$($CORPUS mwe "a b" "d / e" < <(echo "${FS}a b\na b a  b c d / e"))" "$(echo "${FS}a b\na_b a_b c d_/_e")"

#split
echo "${FS}a\naaa\n${FS}b\nbbb" | $CORPUS split
[[ -f a ]]
assert 'split a' $? 0
[[ -f b ]]
assert 'split b' $? 0
assert 'split a contents' "$(cat a)" 'aaa'
assert 'split b contents' "$(cat b)" 'bbb'
teardown

#stopwords
#types
assert 'types' "$(echo 'a\nb\nc' | $CORPUS stopwords <(echo 'a\nc'))" 'b'

#tokens
assert 'tokens' "$(echo 'a b c' | $CORPUS tokens)" "$(echo 'a\nb\nc')"
assert 'detokenize' "$(echo 'a b c' | $CORPUS tokens | $CORPUS detokenize)" "$(echo 'a b c')"

#types
assert 'types' "$(echo 'c a b b c' | $CORPUS types)" "$(echo 'a\nb\nc')"

[[ -z "$ERR" ]] && echo "All Tests Pass"
exit "$ERR"


